spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: ${DATABASE_PASSWORD:my-secret-pw}
    url: jdbc:mysql://${DATABASE_HOST:localhost}:${DATABASE_PORT:3307}/${DATABASE_NAME:db_test123}?createDatabaseIfNotExist=${CREATE_DATABASE:true}
    username: ${DATABASE_USERNAME:root}
  flyway:
    validate-on-migrate: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  #    createSchemas: false
  #    schemas: ${DATABASE_NAME:db_test12}
  #    enabled: ${SPRING_FLYWAY_ENABLED:false}
  redis:
    #    host: ${SPRING_REDIS_HOST:10.0.222.163}
    host: ${SPRING_REDIS_HOST:localhost}
    port: ${SPRING_REDIS_PORT:6379}