DROP PROCEDURE IF EXISTS db_test.sp_student;

DELIMITER $$
CREATE PROCEDURE sp_student(
    IN P_PAGE_BEGIN INT
, IN P_PAGE_END INT
)
BEGIN

    SELECT *
    FROM (SELECT ROW_NUMBER() OVER (ORDER BY ID) AS INTROW,
                 ST.*
          FROM ele_hrm_db.student ST) S
    WHERE S.INTROW BETWEEN P_PAGE_BEGIN AND P_PAGE_END;
END$$
DELIMITER ;