-- ${flyway:timestamp}
DROP PROCEDURE IF EXISTS sp_student;

DELIMITER $$

CREATE PROCEDURE sp_student(
    IN P_PAGE_BEGIN INT
, IN P_PAGE_END INT
)
BEGIN

    SELECT *
    FROM (SELECT ROW_NUMBER() OVER (ORDER BY ID) AS INTROW,
                 ST.id
          FROM students ST) S
    WHERE S.INTROW BETWEEN P_PAGE_BEGIN AND P_PAGE_END;
END$$
DELIMITER ;